Repository aio-libs/aiosmtpd, pull requests merged in 2020-12, with the labels that each got.

#193 Fix ConnectionResetError when the client disconnected
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/handlers.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_smtp.py
  housekeep.py
  tox.ini
Labels: bug, compatibility, ready-to-merge

#59 Handle long lines
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_smtp.py
Labels: blocker, bug, rfc/standards compliance

#213 Catch exceptions raised by Controller.factory()
  .coveragerc
  aiosmtpd/controller.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/controller.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_lmtp.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_server.py
  aiosmtpd/tests/test_smtp.py
  aiosmtpd/tests/test_smtps.py
  aiosmtpd/tests/test_starttls.py
Labels: bug

#196 Don't Edit User-Supplied TLS Context
  .coveragerc
  .github/workflows/unit-testing-and-coverage.yml
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/lmtp.py
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_smtp.py
  aiosmtpd/tests/test_smtps.py
  aiosmtpd/tests/test_starttls.py
  housekeep.py
  tox.ini
Labels: bug
