Repository aio-libs/aiosmtpd, pull requests merged in 2021-01, with the labels that each got.

#225 Workaround to specify additional AUTH mechanisms with dash
  .gitignore
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/handlers.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_smtp.py
Labels: bug

#207 Make LHLO behave like EHLO
  MANIFEST.in
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/lmtp.py
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_lmtp.py
  aiosmtpd/tests/test_starttls.py
  coverage.cfg
  housekeep.py
  tox.ini
Labels: rfc/standards compliance

#222 Command Call Limit
  README.rst
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/lmtp.py
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_smtp.py
Labels: security

#228 Change unit testing runner to Pytest
  .appveyor.yml
  .gitignore
  MANIFEST.in
  README.rst
  aiosmtpd/controller.py
  aiosmtpd/docs/intro.rst
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_server.py
  aiosmtpd/tests/test_smtp.py
  conf.py
  coverage.cfg
  housekeep.py
  pyproject.toml
  release.py
  setup.cfg
  setup.py
  setup_helpers.py
  tox.ini
  unittest.cfg
Labels: testing

#232 BUGFIX: RFC4954 behavior for lone "="
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/handlers.rst
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/tests/test_smtp.py
Labels: bug, rfc/standards compliance

#234 Hide password in logs
  .gitignore
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/tests/test_smtp.py
Labels: security

#236 Properly apply Apache-2.0 license
  LICENSE
  NOTICE
  aiosmtpd/controller.py
  aiosmtpd/handlers.py
  aiosmtpd/lmtp.py
  aiosmtpd/main.py
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_lmtp.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_server.py
  aiosmtpd/tests/test_smtp.py
  aiosmtpd/tests/test_smtps.py
  aiosmtpd/tests/test_starttls.py
  examples/basic/client.py
  examples/basic/server.py
  housekeep.py
  release.py
Labels: administrivia, ready-to-merge, tech-debt

#230 Remove bpo-27931 workaround
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_smtp.py
Labels: ready-to-merge, tech-debt

#157 Allow handle_EHLO to change the responses to EHLO
  .github/workflows/unit-testing-and-coverage.yml
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/handlers.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_smtp.py
  conf.py
  tox.ini
Labels: enhancement, ready-to-merge

#238 Better Documentation & README
  README.rst
  _static/.ignore
  _static/aiosmtpd.css
  _static/css/aiosmtpd.css
  aiosmtpd/docs/controller.rst
  aiosmtpd/docs/index.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/smtp.py
  conf.py
Labels: documentation, ready-to-merge

#218 Improved authenticator system
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_smtp.py
  setup.cfg
Labels: enhancement, ready-to-merge
