Repository aio-libs/aiosmtpd, pull requests merged in 2021-02, with the labels that each got.

#242 FIX for "No module named 'public'" during installation
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/conf.py
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_server.py
  setup.cfg
Labels: compatibility, ready-to-merge

#202 Convert all test cases to pytest
  .github/workflows/unit-testing-and-coverage.yml
  .gitignore
  MANIFEST.in
  README.rst
  _static/aiosmtpd.css
  aiosmtpd/__init__.py
  aiosmtpd/__main__.py
  aiosmtpd/controller.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/conf.py
  aiosmtpd/docs/controller.rst
  aiosmtpd/docs/index.rst
  aiosmtpd/docs/requirements.txt
  aiosmtpd/docs/testing.rst
  aiosmtpd/handlers.py
  aiosmtpd/lmtp.py
  aiosmtpd/main.py
  aiosmtpd/py.typed
  aiosmtpd/qa/__init__.py
  aiosmtpd/qa/test_0packaging.py
  aiosmtpd/qa/test_1testsuite.py
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/testing/statuscodes.py
  aiosmtpd/tests/conftest.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_lmtp.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_server.py
  aiosmtpd/tests/test_smtp.py
  aiosmtpd/tests/test_smtps.py
  aiosmtpd/tests/test_starttls.py
  housekeep.py
  pyproject.toml
  release.py
  setup.cfg
  setup.py
  tox.ini
Labels: ready-to-merge, testing

#248 Fix Controller Bug on hostname="" or IPv6 not available
  .github/workflows/unit-testing-and-coverage.yml
  aiosmtpd/__init__.py
  aiosmtpd/controller.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/controller.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_server.py
  release.py
Labels: bug

#250 Fix ipv6 detection
  DESCRIPTION.rst
  README.rst
  aiosmtpd/__init__.py
  aiosmtpd/controller.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/controller.rst
  aiosmtpd/tests/test_server.py
  housekeep.py
  release.py
  setup.cfg
  tox.ini
Labels: bug, documentation

#246 Implement support for PROXY Protocol
  aiosmtpd/__init__.py
  aiosmtpd/__main__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/conf.py
  aiosmtpd/docs/handlers.rst
  aiosmtpd/docs/index.rst
  aiosmtpd/docs/proxyprotocol.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/main.py
  aiosmtpd/proxy_protocol.py
  aiosmtpd/smtp.py
  aiosmtpd/testing/helpers.py
  aiosmtpd/testing/statuscodes.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_proxyprotocol.py
  housekeep.py
  setup.cfg
  tox.ini
Labels: enhancement

#249 New Example: authrelay (shows off AUTH system)
  .github/workflows/unit-testing-and-coverage.yml
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/auth.rst
  examples/authenticated_relayer/.gitignore
  examples/authenticated_relayer/__init__.py
  examples/authenticated_relayer/make_user_db.py
  examples/authenticated_relayer/requirements.txt
  examples/authenticated_relayer/server.py
  housekeep.py
  release.py
  tox.ini
Labels: documentation

#252 Add SSL support (SMTPS/STARTTLS) to CLI
  .github/workflows/unit-testing-and-coverage.yml
  README.rst
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/_exts/autoprogramm.py
  aiosmtpd/docs/conf.py
  aiosmtpd/docs/manpage.rst
  aiosmtpd/main.py
  aiosmtpd/qa/test_0packaging.py
  aiosmtpd/tests/conftest.py
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_server.py
  bandit.yml
  housekeep.py
  tox.ini
Labels: CLI, enhancement

#254 Fix "pypy3" testenv on Windows, Fix MacOS flakeyness
  .gitignore
  README.rst
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/tests/test_main.py
  aiosmtpd/tests/test_proxyprotocol.py
  housekeep.py
  pyproject.toml
  setup.cfg
  tox.ini
Labels: documentation, testing

#247 Implement Unix Socket Controller
  .github/workflows/unit-testing-and-coverage.yml
  .gitignore
  aiosmtpd/__init__.py
  aiosmtpd/controller.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/conf.py
  aiosmtpd/docs/controller.rst
  aiosmtpd/docs/smtp.rst
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_server.py
  pyproject.toml
  setup.cfg
  tox.ini
Labels: API, enhancement

#255 Add New Badge + reorder
  DESCRIPTION.rst
  README.rst
Labels: documentation
