Repository aio-libs/aiosmtpd, pull requests merged in 2022-12, with the labels that each got.

#324 Enhance GitHUB CI Workflow
  .github/workflows/unit-testing-and-coverage.yml
  tox.ini
Labels: integration, testing, ready-to-merge

#328 Bump to 1.4.3
  .gitignore
  DESCRIPTION.rst
  MANIFEST.in
  README.rst
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  aiosmtpd/docs/controller.rst
  setup.cfg
  tox.ini
Labels: integration, documentation

#267 Explicitly require setuptools, tests/test_smtps.py and tests/test_starttls.py imports pkg_resources
  setup.cfg
Labels: integration

#336 Bump 1.4.3 final (for release!)
  aiosmtpd/__init__.py
  aiosmtpd/docs/NEWS.rst
  tox.ini
Labels: ready-to-merge

#339 GHCI Improvements 2
  .github/workflows/unit-testing-and-coverage.yml
  README.rst
Labels: integration

#342 Minor readme fixes
  DESCRIPTION.rst
  README.rst
Labels: documentation

#348 Fix CodeQL Findings 2022-12-23
  DESCRIPTION.rst
  README.rst
  aiosmtpd/controller.py
  aiosmtpd/docs/_exts/autoprogramm.py
  aiosmtpd/proxy_protocol.py
  aiosmtpd/smtp.py
  aiosmtpd/tests/test_handlers.py
  aiosmtpd/tests/test_proxyprotocol.py
  examples/authenticated_relayer/server.py
  examples/basic/server.py
Labels: ready-to-merge, code-quality

#352 Remove Discourse, replace with GH Discussions
  DESCRIPTION.rst
  README.rst
Labels: documentation, administrivia

#357 setDaemon() is deprecated, set the daemon attrib directly instead
  aiosmtpd/docs/controller.rst
  aiosmtpd/tests/test_server.py
Labels: tech-debt

#358 Change tox behavior
  tox.ini
Labels: testing

#359 Drop testing for PyPy3.6, add PyPy3.9
  .github/workflows/unit-testing-and-coverage.yml
  README.rst
Labels: testing
